version: '3'
services:

  redis.socket:
    image: 'redis:alpine'
    volumes:
      - './volumes/redis/socket:/data'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - spu011_network

  redis.cache:
    image: 'redis:alpine'
    volumes:
      - './volumes/redis/cache:/data'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - spu011_network

networks:
  spu011_network:
    driver: bridge
