version: '3'
services:

  storage:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9009:9009"
    volumes:
      - ./volumes/storage:/data
    env_file:
      - .env
    command: server --console-address :9009 /data
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - spu011_network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - spu011_network
    depends_on:
      - front.vue
      - socket.jonny
    ports:
      - "80:80"

  front.vue:
    build: ./front_vue
    volumes:
      - ./front_vue:/usr/src/app
    command: sh -c " npm install && npm start "
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - spu011_network

  redis.socket:
    image: 'redis:alpine'
    volumes:
      - './volumes/redis/socket:/data'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - spu011_network

  redis.cache:
    image: 'redis:alpine'
    volumes:
      - './volumes/redis/cache:/data'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - spu011_network

  socket.jonny:
      build: ./sockets
      volumes:
        - ./sockets:/usr/src/app
      command: sh -c " npm install && npm start "
      extra_hosts:
        - 'host.docker.internal:host-gateway'
      networks:
        - spu011_network
      depends_on:
        - redis.socket
        - redis.cache
      environment:
        - NAME=Jonny
      env_file:
        - .env


networks:
  spu011_network:
    driver: bridge

